import { RequestRow } from "@/components/dashboard/requests/types";

export const demoRequests: RequestRow[] = [
  {
    id: "demo-req-1",
    jobberAccountId: "demo-account",
    status: "NEW",
    createdAt: new Date().toISOString(),
    title: "Summer turnover cleaning",
    contactName: "Mara DeSoto",
    address: {
      line1: "1105 Lighthouse Rd",
      city: "Southold",
      state: "NY",
      postalCode: "11971",
      country: "USA",
    },
    addressString: "1105 Lighthouse Rd, Southold, NY 11971",
    enrichment: null,
    raw: { serviceType: "cleaning" },
  },
  {
    id: "demo-req-2",
    jobberAccountId: "demo-account",
    status: "SCHEDULED",
    createdAt: new Date(Date.now() - 1000 * 60 * 40).toISOString(),
    title: "Exterior pressure wash",
    contactName: "Greg Hale",
    address: {
      line1: "410 Carpenter St",
      city: "Greenport",
      state: "NY",
      postalCode: "11944",
      country: "USA",
    },
    addressString: "410 Carpenter St, Greenport, NY 11944",
    enrichment: null,
    raw: { serviceType: "pressure_washing" },
  },
  {
    id: "demo-req-3",
    jobberAccountId: "demo-account",
    status: "COMPLETED",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
    title: "Window washing + screens",
    contactName: "Lisa Moretti",
    address: {
      line1: "2870 Haywater Cove",
      city: "Cutchogue",
      state: "NY",
      postalCode: "11935",
      country: "USA",
    },
    addressString: "2870 Haywater Cove, Cutchogue, NY 11935",
    enrichment: null,
    raw: { serviceType: "window_washing" },
  },
  {
    id: "demo-req-4",
    jobberAccountId: "demo-account",
    status: "NEW",
    createdAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    title: "Weekly lawn care",
    contactName: "Aaron Kupfer",
    address: {
      line1: "1455 Boisseau Ave",
      city: "Southold",
      state: "NY",
      postalCode: "11971",
      country: "USA",
    },
    addressString: "1455 Boisseau Ave, Southold, NY 11971",
    enrichment: null,
    raw: { serviceType: "lawn_care" },
  },
  {
    id: "demo-req-5",
    jobberAccountId: "demo-account",
    status: "SCHEDULED",
    createdAt: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    title: "Handyman punch list",
    contactName: "Julia Gatz",
    address: {
      line1: "1265 Kenney Rd",
      city: "Southold",
      state: "NY",
      postalCode: "11971",
      country: "USA",
    },
    addressString: "1265 Kenney Rd, Southold, NY 11971",
    enrichment: null,
    raw: { serviceType: "handyman" },
  },
];
